### PR TITLE
Added support for breaking change in eslint v6+

### PR DESCRIPTION
**Pull request by roniger**

### CODE REVIEW

**Comment by pladaria** [comment]
Please, accept this PR

**Comment by gabegorelick** [comment]
Better approach is to not rely on internal ESLint functions at all. See https://github.com/vuejs/eslint-plugin-vue/pull/910 for comparison.

**Comment by roniger** [comment]
Agreed. Are you making the change?

**Comment by gabegorelick** [comment]
I would be happy to, but since there is no indication that any PR will get merged (none since 2017), I wasn't planning on it. See the (currently one-sided) discussion on https://github.com/zertosh/eslint-plugin-dependencies/issues/23.

**Comment by roniger** [comment]
Yes, it does look abandoned. I gave up on this initiative a while ago
Doesn't seem like there will be any feedback any time soon

**Comment by AdrieanKhisbe** [comment]
@roniger @gabegorelick 

I considered at some point doing a published fork, but give up when realised that the [plugin `eslint-plugin-import`](https://github.com/benmosher/eslint-plugin-import) does the job (and way more)

### Here are the equivalent rules:
- `dependencies/no-cycles` -> `import/no-cycle`: [doc](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-cycle.md)
- `dependencies/no-unresolved` + `dependencies/case-sensitive` -> `import/no-unresolved`: [doc](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md)
  -  ⚠️ beware option is needed for `require` (`{"commonjs": true}`)
  - for case sensitivity use the [`caseSensitive` option](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md#casesensitive)
- `dependencies/require-json-ext` -> `import/extensions`: [doc](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/extensions.md)

### Here is the list of all the rules: https://github.com/benmosher/eslint-plugin-import#rules

**Comment by AdrieanKhisbe** [comment]
☝️ 

 that could interest you too @pladaria :)

and also everyone that 👍 the issues and [comment](https://github.com/zertosh/eslint-plugin-dependencies/pull/21#issuecomment-506262327)
@despairblue, @Stegoo, @edi9999, @lynxtaa, @yelworc, @AdriVanHoudt, @mkamakura, @ErideDLF, @d2phap, @lynxtaa, @oknechirik

**Comment by gabegorelick** [comment]
`import/no-cycle` doesn't work for commonjs.

**Comment by mrtnzlml** [comment]
@AdrieanKhisbe We did [exactly the same](https://github.com/kiwicom/eslint-config-kiwicom/blob/master/CHANGELOG.md#4110) long time ago! 👍

**Comment by pladaria** [comment]
@AdrieanKhisbe sadly `import/no-cycle` doesn't work well with flowtype
https://github.com/benmosher/eslint-plugin-import/issues/1343

We finally did an internal fork of this plugin

**Comment by dominicfraser** [comment]
@pladaria, would this fix your issue? 

https://github.com/benmosher/eslint-plugin-import/pull/1494

**Review by jeffreyc86 — APPROVED** [review]

**Comment by jeffreyc86** [comment]
@zertosh - Hi can you you please approve and merge this PR? theres a breaking change due to folder restructuring from eslint version updates

**Comment by zertosh** [comment]
Published as [2.5.0](https://www.npmjs.com/package/eslint-plugin-dependencies/v/2.5.0)

**Pull request closed without merging**
